### ISSUE TITLE
hc0_linux.h: hc_tri misses one pixel

### ISSUE THREAD

**Issue by aolo2** [baines/halcyon#2]
The provided ```hc_tri``` function misses one pixel in some cases. I'm not too sure what the conditions are (the vertex order maybe?). Seems like an off-by-one error.

Full repro:

```
#define WHITE 0xFFFFFFFF

#include "hc0_linux.h"

static void
draw_quad(hc_v2 pos, int8_t side)
{
    hc_v2 a = { pos.x + side, pos.y + side };
    hc_v2 b = { pos.x + side, pos.y };
    hc_v2 c = { pos.x, pos.y + side };
    hc_v2 d = { pos.x, pos.y };
    hc_tri(a, b, c, WHITE, WHITE);
//    hc_tri(b, d, c, WHITE, WHITE);
}

int32_t
main(int32_t argc, char *argv[])
{
    hc_init("");

    for (;;) {
        hc_v2 pos = { WIN_W / 2, WIN_H / 2 };
        draw_quad(pos, 10);
        hc_finish(HC_CLEAR);
    }

    return(0);
}
```

The code above results in this image (the bottom-right pixel is missing):
![image](https://user-images.githubusercontent.com/17429989/65150409-be70f200-da2c-11e9-9efb-4f6d4bab8a7d.png)

**Comment by baines** [comment]
Thanks.

I saw the line_step functions in `hc0_linux.h` were outdated compared to the multi-file lib so updated them, but after trying the test case it was still incorrect - so I have done a quick fix to call `plot` once more at the end of these functions in acfd7e2.

There's probably a more elegent solution but this seemed to work fine for the test case and didn't negatively affect the other programs.

**Comment by baines** [comment]
Closing since I believe it is fixed. If not, feel free to reopen.
